import { useApp } from '../context/AppContext.jsx';
import SandboxViewer from './SandboxViewer.jsx';

export default function VisualizationPanel() {
  const { vizPanel, closeVizPanel } = useApp();

  if (vizPanel !== 'sandbox') return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8">
      <button
        type="button"
        className="absolute inset-0 bg-yale-900/70 backdrop-blur-sm"
        aria-label="Close visualization"
        onClick={closeVizPanel}
      />

      <div className="relative w-full max-w-3xl h-[min(85vh,720px)] flex flex-col bg-white border border-slate-200 rounded-xl shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-200 bg-slate-50 shrink-0">
          <div>
            <h2 className="text-sm font-bold text-slate-900">AI sandbox visualization</h2>
            <p className="text-[10px] font-mono text-slate-500 mt-0.5">Generated by tutor</p>
          </div>
          <button
            type="button"
            onClick={closeVizPanel}
            className="px-3 py-1.5 text-xs font-medium text-slate-600 hover:text-slate-900 rounded-lg hover:bg-slate-200"
          >
            Close
          </button>
        </div>

        <div className="flex-1 min-h-0 relative bg-[#090d16]">
          <SandboxViewer />
        </div>
      </div>
    </div>
  );
}
